### ISSUE TITLE
[JSCS][Report][Support] Report data is not matching.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#21]
https://avni.freshdesk.com/a/tickets/657

Reports - 
Count all ANC/Non-ANC - https://reporting.openchs.org/question/299
Report for Users - https://reporting.openchs.org/question/300
Complete report (887 -including Voided) - https://reporting.openchs.org/question/783
Line list of all SS Genotype cases - https://reporting.openchs.org/question/275
Line list of all registered beneficiaries	- https://reporting.openchs.org/question/218

**Comment by vindeolal** [comment]
There was a problem with the voided entities in some reports we don't take voided individuals while in some we don't consider voided individuals and enrolments. Made it uniform by not considering voided individuals and enrolments in all the reports except the "Complete report". In "complete report" added a column "enrolment voided" so that records can be filtered and matched with other reports.
