### ISSUE TITLE
[JSCS][Support] report fixes.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#26]
1. **Number mismatch in the following reports -** (https://avni.freshdesk.com/a/tickets/657)
Total Enrolment in following reports - 
i. Count all anc/non-anc - 47,325 - https://reporting.avniproject.org/question/299
ii. All registered beneficiaries - 47,325 - https://reporting.avniproject.org/question/218
iii. Complete report - 49,289 (there are duplicate entries) - https://avni.freshdesk.com/a/tickets/793
iv. Report for users - 47,361 - https://reporting.avniproject.org/question/300

2. **Number mismatch in the report - Report for user (**https://avni.freshdesk.com/a/tickets/805)
In this report total number of ANC+Non-ANC is not equal to total enrolments.
https://reporting.avniproject.org/question/300

3. **Duplicate data in the report - Complete report** - (https://avni.freshdesk.com/a/tickets/793)
https://reporting.avniproject.org/question/783

**Comment by vindeolal** [comment]
@garimadosar5 these issues are fixed.
- There was an issue with the metabase cache when they were trying to compare the numbers across reports. Currently there is no way to reset the cache from UI.
- There was a bug in the Report for user, fixed it.
- For the Complete report, fixed the duplication issue. But because the data is huge, file is not getting downloaded. Here are some options that can be done.
1. We can give a individual name filter and only that record will show up in the report.
2. We download the data in chunks, e.g. first we download the first 5K records and then next 5K records and so on.
We can ask them the use case and propose these options for Complete report.
