### ISSUE TITLE
[JSCS] Sickle cell testing data collection form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#30]
**Document -**  https://docs.google.com/document/d/18-CZWq-9iM0fEieNjWXzKpMDacL6zOm5BsLAfTcsNio/edit

**Subject type -** Lab Facility
**Reg form-** 
https://docs.google.com/spreadsheets/d/155tFDCBUxiHRgS-gVg-rCMc0HeInxSF4o2qa392GzAE/edit#gid=0
1. Name of Lab facility
2. District
3. Block

**General encounter (New form) -**
https://docs.google.com/spreadsheets/d/155tFDCBUxiHRgS-gVg-rCMc0HeInxSF4o2qa392GzAE/edit#gid=182836146

_Scheduling -_ 
- Schedule on 01st of every month and data for last month will be filled.
- Overdue after 15 days.
- No cancel option

**Comment by vindeolal** [comment]
This is set up in JSCS UAT org.

**Some changes done in the encounter form**
- Question "Select Month" is not added, instead of asking month, we'll append month and year in the visit being scheduled. So if a visit is scheduled for July month then the visit name will be "Sickle cell testing entry for Jun 2021".

- For testing this please take the latest app from the master branch, there was a bug in the validation rule that was fixed in the platform.

**Comment by garimadosar5** [comment]
QA Points - 
- How earliest and max visit date is calculated?
- Validation rule is wrong.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Number of non-pregnant screened cases SHOULD NOT BE less than solubility Positive 
- Solubility Positive for non-pregnant SHOULD NOT BE less than AS + SS
- Number of pregnant screened cases SHOULD NOT BE less than solubility Positive 
- Solubility Positive for pregnant SHOULD NOT BE less than AS + SS

**Comment by vindeolal** [comment]
- Validation rule is fixed as per the mentioned logic.
