### ISSUE TITLE
[JSCS] Diagnostic Report card printing.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#39]
Ref Folder - https://drive.google.com/drive/folders/1q7JeTAhg06PyPQqaVCF0mZzgxdKOCTqO

Front of the report for SS - 
https://docs.google.com/document/d/1iAR1uc-JGtmBmkCEmVTo9dB6Q5DS9ksF/edit

Front of the report for AS - 
https://docs.google.com/document/d/1V7TIdwBvyV4S7KGK4DooznG2dCIHCwvw/edit?rtpof=true

Backside of the report for SS - 
https://docs.google.com/document/d/1RT7OLzd4CYoZJn-oDLcseirwpqU0l70L/edit

Backside of the report for AS - 
https://docs.google.com/document/d/1LeY4TKeVc1oTMikab5CXCs-GFOdBTF2S/edit?rtpof=true

**Comment by vindeolal** [comment]
This is dependent on Custom columns on the search result page feature. Moving it on hold.

**Comment by vindeolal** [comment]
SS report printing feedback -
1. There is overlapping of texts during the print of backside contents. Please refer to screenshot 1. 
2. I am attaching the updated content of the backside, please find the attached file with the name "Report back SS.docx" and kindly update the content. 
3. I was trying to check the format of AS persons but couldn't be tried because no AS person is there in the registered persons. When I tried to enrol a person as AS the enrolment number is not generating in the UAT app from my ID.  Check Screenshot 2.
4. Content on front side of SS person's report is fine.

**Comment by garimadosar5** [comment]
QA Notes - 
- Giving this error on print. I have selected cases with SS genotype.
![Screenshot from 2021-09-14 12-44-59.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/e9a50674-b317-4996-b41a-c37ae5bb53ca)

**Comment by vindeolal** [comment]
@garimadosar5 Please provide more details. For which subject are you getting this error? Also which user are you trying this with?

**Comment by garimadosar5** [comment]
QA Notes - 
 - If a non SS/AS patient is choosen for printing then, it shows the message but it continues loading the page and once "OK" button is clicked. It take to print page and a blank page is there for printing.
There should not be any loading of page and OK button should take to previuos page i.e. list of patients.

- If there are more than one patients selected and all are not eligible for printing then it does not give any message why it is not printing all the cases.
