### ISSUE TITLE
[JSCS] Patient Card Printing for SS Patient

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#40]
Ref folder - 
https://drive.google.com/drive/folders/1q7JeTAhg06PyPQqaVCF0mZzgxdKOCTqO

Frontside - https://docs.google.com/document/d/1SUlzLdSQYOHpoC4kW9JiPyHMHSxaYVrd/edit

Backside - 
https://docs.google.com/document/d/1p64GUXbj-JCVQFtSpnAhyOGR02WAWKeh/edit?rtpof=true

**Comment by vindeolal** [comment]
This is dependent on the server-side ID generation feature. Moving it to on Hold.

**Comment by vindeolal** [comment]
SS Card print feedback - 
5. SS cards formats are almost as per the need, there is small need of following modifications. For numbering of modification please refer screenshot 3
1. Address seems to be not complete, it is taking only district, not whole address.
2. Please remove the name of SRIJAN, now we have decided to not keep the name of srijan in the cards & reports of patients. 
3. Please do the centre alignment of the texts and Anuppur should be in the 2nd line instead of the 1st line. First-line should contains only the name of project. Also the name of district should be changed in this line based on the address of the patient. If he belongs to Dindori then project heading should have Dindori instead of Anuppur.

**Comment by garimadosar5** [comment]
QA Notes - 
- Giving this error even on selecting SS patients.
![Screenshot from 2021-09-14 12-39-22.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/a6b66d1a-6ad3-45df-ac57-05793adfb2e6)

**Comment by vindeolal** [comment]
@garimadosar5 Please provide more details. For which subject are you getting this error? Also which user are you trying this with?

**Comment by garimadosar5** [comment]
QA Notes - 
- If a non SS patient is choosen for printing then, it shows the message but it continues loading the page and once "OK" button is clicked. It take to print page and a blank page is there for printing.

There should not be any loading of page and OK button should take to previuos page i.e. list of patients.

**Comment by vindeolal** [comment]
Fixed

**Comment by vindeolal** [comment]
- The first one is fixed.
- For the second one, even if there is one ss/as patient we print those skipping others. we don't give error in that case.
